swagger: "2.0"
info:
  title: "Secure API"
  version: "1.0.0"
host: attacker.com
paths:
  /login:
    post:
      summary: "User Login"
      parameters:
        - in: formData
          name: username
          type: string
        - in: formData
          name: password
          type: string
      responses:
        200:
          description: "Successful login"
